[tool.poetry]
name = "tptq.feacomposer"
version = "1.4.0"
description = "A feaLib wrapper for composing FEA code in Python"
license = "MIT"
authors = ["Liang Hai <liang@typotheque.com>"]
readme = "README.md"
repository = "https://github.com/typotheque/feacomposer"
packages = [{ include = "tptq" }]

[tool.poetry.dependencies]
python = "^3.10"
fonttools = "^4.43.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
